# Generated by Django 2.1.2 on 2018-10-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
                ('description', models.TextField(verbose_name='解説')),
            ],
        ),
    ]
